export class CarConstants {
  public static CAR_DETAILS = [
    {
      "model": "Volkswagen Jetta", "model_id": "75822", "model_make_id": "Volkswagen", "model_name": "Jetta",
      "model_trim": "GLI SEL 4dr Sedan (2.0L 4cyl Turbo 6A)", "model_year": "2019", "model_body": "Compact Cars",
      "model_engine_position": "Front", "model_engine_cc": "2000", "model_engine_cyl": "4", "model_engine_type": "Inline",
      "model_engine_valves_per_cyl": "4", "model_engine_power_ps": "210", "model_engine_power_rpm": null,
      "model_engine_torque_nm": "207", "model_engine_torque_rpm": null, "model_engine_bore_mm": null,
      "model_engine_stroke_mm": null, "model_engine_compression": "9.6", "model_engine_fuel": "Premium Unleaded (Recommended)",
      "model_top_speed_kph": null, "model_0_to_100_kph": null, "model_drive": "Front Wheel Drive",
      "model_transmission_type": "Automatic", "model_seats": null, "model_doors": "4", "model_weight_kg": "3124",
      "model_length_mm": null, "model_width_mm": null, "model_height_mm": null, "model_wheelbase_mm": null,
      "model_lkm_hwy": "32.0", "model_lkm_mixed": "27.0", "model_lkm_city": "24.0", "model_fuel_cap_l": "15",
      "model_sold_in_us": "1", "model_co2": null, "model_make_display": "Volkswagen", "model_engine_l": "2.0",
      "model_engine_ci": "122", "model_engine_bore_in": null, "model_engine_stroke_in": null, "model_engine_valves": "16",
      "model_engine_power_hp": "207", "model_engine_power_kw": "154", "model_engine_torque_lbft": "153",
      "model_engine_torque_kgm": "21", "model_top_speed_mph": null, "model_weight_lbs": "6887", "model_length_in": null,
      "model_width_in": null, "model_height_in": null, "model_wheelbase_in": null, "model_mpg_hwy": "7",
      "model_mpg_city": "10", "model_mpg_mixed": "9", "model_fuel_cap_g": "4.0", "make_display":
        "Volkswagen", "make_country": "Germany", "ExtColors": [], "IntColors": []
    },
    {
      "model": "Ford Mustang", "model_id": "73974", "model_make_id": "Ford", "model_name": "Mustang", "model_trim": "EcoBoost 2dr Coupe (2.3L 4cyl Turbo 6M)", "model_year": "2019", "model_body": "Subcompact Cars", "model_engine_position": "Front", "model_engine_cc": "2300", "model_engine_cyl": "4", "model_engine_type": "Inline", "model_engine_valves_per_cyl": "4", "model_engine_power_ps": "310", "model_engine_power_rpm": null, "model_engine_torque_nm": "320", "model_engine_torque_rpm": null, "model_engine_bore_mm": null, "model_engine_stroke_mm": null, "model_engine_compression": "9.5", "model_engine_fuel": "Premium Unleaded (Recommended)", "model_top_speed_kph": null, "model_0_to_100_kph": null, "model_drive": "Rear Wheel Drive", "model_transmission_type": "Manual", "model_seats": null, "model_doors": "2", "model_weight_kg": null, "model_length_mm": null, "model_width_mm": null, "model_height_mm": null, "model_wheelbase_mm": null, "model_lkm_hwy": "31.0", "model_lkm_mixed": "26.0", "model_lkm_city": "22.0", "model_fuel_cap_l": "16", "model_sold_in_us": "1", "model_co2": null, "model_make_display": "Ford", "model_engine_l": "2.3", "model_engine_ci": "140", "model_engine_bore_in": null, "model_engine_stroke_in": null, "model_engine_valves": "16", "model_engine_power_hp": "306", "model_engine_power_kw": "228", "model_engine_torque_lbft": "236", "model_engine_torque_kgm": "33", "model_top_speed_mph": null, "model_weight_lbs": null, "model_length_in": null, "model_width_in": null, "model_height_in": null, "model_wheelbase_in": null, "model_mpg_hwy": "8", "model_mpg_city": "11", "model_mpg_mixed": "9", "model_fuel_cap_g": "4.2", "make_display": "Ford", "make_country": "USA", "ExtColors": [], "IntColors": []
    },
    {
      "model": "Audi Q5", "model_id": "74923", "model_make_id": "Audi", "model_name": "Q5", "model_trim": "TDI Prestige quattro 4dr SUV AWD (3.0L 6cyl Turbodiesel 8A)", "model_year": "2019", "model_body": "Sport Utility Vehicles", "model_engine_position": "Front", "model_engine_cc": "3000", "model_engine_cyl": "6", "model_engine_type": "V", "model_engine_valves_per_cyl": "4", "model_engine_power_ps": "240", "model_engine_power_rpm": null, "model_engine_torque_nm": "428", "model_engine_torque_rpm": null, "model_engine_bore_mm": null, "model_engine_stroke_mm": null, "model_engine_compression": "Not Avai", "model_engine_fuel": "Diesel", "model_top_speed_kph": null, "model_0_to_100_kph": null, "model_drive": "All Wheel Drive", "model_transmission_type": "Automatic", "model_seats": null, "model_doors": "4", "model_weight_kg": "4475", "model_length_mm": null, "model_width_mm": null, "model_height_mm": null, "model_wheelbase_mm": null, "model_lkm_hwy": "31.0", "model_lkm_mixed": "27.0", "model_lkm_city": "24.0", "model_fuel_cap_l": "20", "model_sold_in_us": "1", "model_co2": null, "model_make_display": "Audi", "model_engine_l": "3.0", "model_engine_ci": "183", "model_engine_bore_in": null, "model_engine_stroke_in": null, "model_engine_valves": "24", "model_engine_power_hp": "237", "model_engine_power_kw": "177", "model_engine_torque_lbft": "316", "model_engine_torque_kgm": "44", "model_top_speed_mph": null, "model_weight_lbs": "9866", "model_length_in": null, "model_width_in": null, "model_height_in": null, "model_wheelbase_in": null, "model_mpg_hwy": "8", "model_mpg_city": "10", "model_mpg_mixed": "9", "model_fuel_cap_g": "5.3", "make_display": "Audi", "make_country": "Germany", "ExtColors": [], "IntColors": []
    },
    {
      "model": "Jeep Wrangler", "model_id": "76388", "model_make_id": "Jeep", "model_name": "Wrangler", "model_trim": "Freedom Edition 2dr SUV 4WD (3.6L 6cyl 6M)", "model_year": "2019", "model_body": "Sport Utility Vehicles", "model_engine_position": "Front", "model_engine_cc": "3600", "model_engine_cyl": "6", "model_engine_type": "V", "model_engine_valves_per_cyl": "4", "model_engine_power_ps": "285", "model_engine_power_rpm": null, "model_engine_torque_nm": "260", "model_engine_torque_rpm": null, "model_engine_bore_mm": null, "model_engine_stroke_mm": null, "model_engine_compression": "10.2", "model_engine_fuel": "Regular Unleaded", "model_top_speed_kph": null, "model_0_to_100_kph": null, "model_drive": "Four Wheel Drive", "model_transmission_type": "Manual", "model_seats": null, "model_doors": "2", "model_weight_kg": "3785", "model_length_mm": null, "model_width_mm": null, "model_height_mm": null, "model_wheelbase_mm": null, "model_lkm_hwy": "21.0", "model_lkm_mixed": "18.0", "model_lkm_city": "17.0", "model_fuel_cap_l": "19", "model_sold_in_us": "1", "model_co2": null, "model_make_display": "Jeep", "model_engine_l": "3.6", "model_engine_ci": "220", "model_engine_bore_in": null, "model_engine_stroke_in": null, "model_engine_valves": "24", "model_engine_power_hp": "281", "model_engine_power_kw": "210", "model_engine_torque_lbft": "192", "model_engine_torque_kgm": "27", "model_top_speed_mph": null, "model_weight_lbs": "8344", "model_length_in": null, "model_width_in": null, "model_height_in": null, "model_wheelbase_in": null, "model_mpg_hwy": "11", "model_mpg_city": "14", "model_mpg_mixed": "13", "model_fuel_cap_g": "5.0", "make_display": "Jeep", "make_country": "USA", "ExtColors": [], "IntColors": []
    },
    {
      "model": "Chevrolet Silverado 3500HD", "model_id": "74427", "model_make_id": "Chevrolet", "model_name": "Silverado 3500HD", "model_trim": "LT 2dr Regular Cab 4WD LB (6.0L 8cyl 6A)", "model_year": "2019", "model_body": "Standard Pickup Trucks", "model_engine_position": "Front", "model_engine_cc": "6000", "model_engine_cyl": "8", "model_engine_type": "V", "model_engine_valves_per_cyl": "2", "model_engine_power_ps": "360", "model_engine_power_rpm": null, "model_engine_torque_nm": "380", "model_engine_torque_rpm": null, "model_engine_bore_mm": null, "model_engine_stroke_mm": null, "model_engine_compression": "9.6", "model_engine_fuel": "Flex-Fuel (Unleaded\/E85)", "model_top_speed_kph": null, "model_0_to_100_kph": null, "model_drive": "Four Wheel Drive", "model_transmission_type": "Automatic", "model_seats": null, "model_doors": "2", "model_weight_kg": "6281", "model_length_mm": null, "model_width_mm": null, "model_height_mm": null, "model_wheelbase_mm": null, "model_lkm_hwy": null, "model_lkm_mixed": null, "model_lkm_city": null, "model_fuel_cap_l": "36", "model_sold_in_us": "1", "model_co2": null, "model_make_display": "Chevrolet", "model_engine_l": "6.0", "model_engine_ci": "366", "model_engine_bore_in": null, "model_engine_stroke_in": null, "model_engine_valves": "16", "model_engine_power_hp": "355", "model_engine_power_kw": "265", "model_engine_torque_lbft": "280", "model_engine_torque_kgm": "39", "model_top_speed_mph": null, "model_weight_lbs": "13847", "model_length_in": null, "model_width_in": null, "model_height_in": null, "model_wheelbase_in": null, "model_mpg_hwy": null, "model_mpg_city": null, "model_mpg_mixed": null, "model_fuel_cap_g": "9.5", "make_display": "Chevrolet", "make_country": "USA", "ExtColors": [], "IntColors": []
    }
  ]
}
